// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udtzfpebxnfrcgwqwiqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdHpmcGVieG5mcmNnd3F3aXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzYxMDAsImV4cCI6MjA3Mzk1MjEwMH0.kwn6JHIj9rYnusgTGjokE0pManJap-poaHp6X352ycM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});